<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PresentationProfile [
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute type CDATA #REQUIRED>
<!ATTLIST attribute voice CDATA #IMPLIED>
<!ELEMENT literal (#PCDATA)>
<!ATTLIST literal voice CDATA #IMPLIED>
<!ELEMENT text EMPTY>
<!ATTLIST text type CDATA #REQUIRED>
<!ATTLIST text voice CDATA #IMPLIED>
<!ELEMENT tree EMPTY>
<!ATTLIST tree type CDATA #REQUIRED>
<!ATTLIST tree voice CDATA #IMPLIED>
<!ELEMENT value EMPTY>
<!ATTLIST value voice CDATA #IMPLIED>
<!ELEMENT brdots EMPTY>
<!ATTLIST brdots dots CDATA #REQUIRED>
<!ELEMENT bounds EMPTY>
<!ATTLIST bounds type CDATA #REQUIRED>
<!ELEMENT children (separator?, (attribute | conditional | literal | text | value | tree | brdots | bounds)*)>
<!ATTLIST children voice CDATA #IMPLIED>
<!ELEMENT true (literal | attribute | bounds | text | value | tree | children | conditional)*>
<!ELEMENT false (literal | attribute | bounds | text | value | tree | children | conditional)*>
<!ELEMENT conditional ((true , false?) | (false , true?))>
<!ATTLIST conditional type CDATA #REQUIRED>
<!ATTLIST conditional condition CDATA #REQUIRED>
<!ELEMENT event (attribute | conditional | literal | text | value | bounds | brdots | tree | children)*>
<!ATTLIST event name CDATA #REQUIRED>
<!ELEMENT role (event)*>
<!ATTLIST role name CDATA #REQUIRED>
<!ELEMENT separator (literal | brdots)*>
<!ELEMENT presentation (separator? , role*)>
<!ELEMENT device (presentation)>
<!ATTLIST device name CDATA #REQUIRED>
<!ATTLIST device display CDATA #IMPLIED>
<!ELEMENT PresentationProfile (Name , Description , device*)>
<!ATTLIST PresentationProfile xmlns CDATA #IMPLIED>
]>
<PresentationProfile xmlns="http://www.gnome.org/gnopernicus">
  <Name>Verbose</Name>
  <Name xml:lang="ar">بالتفاصيل</Name>
  <Name xml:lang="az">İnteraktiv</Name>
  <Name xml:lang="bg">Подробна информация</Name>
  <Name xml:lang="bn">ভারবোস</Name>
  <Name xml:lang="ca">Escriu més informació</Name>
  <Name xml:lang="cs">Podrobné</Name>
  <Name xml:lang="cy">Llafar</Name>
  <Name xml:lang="da">Ordrig</Name>
  <Name xml:lang="de">Redselig</Name>
  <Name xml:lang="el">Verbose</Name>
  <Name xml:lang="en_CA">Verbose</Name>
  <Name xml:lang="en_GB">Verbose</Name>
  <Name xml:lang="es">Detallado</Name>
  <Name xml:lang="eu">Hitzez hitz</Name>
  <Name xml:lang="fi">Suulas</Name>
  <Name xml:lang="fr">Bavard</Name>
  <Name xml:lang="gu">દેખીતુ</Name>
  <Name xml:lang="hi">वाचाल</Name>
  <Name xml:lang="hr">Opširno</Name>
  <Name xml:lang="it">Prolisso</Name>
  <Name xml:lang="ja">冗長</Name>
  <Name xml:lang="ko">말 많이</Name>
  <Name xml:lang="lt">Išsamus</Name>
  <Name xml:lang="mn">Нуршуу</Name>
  <Name xml:lang="nb">Utdypende</Name>
  <Name xml:lang="nl">Breedsprakig</Name>
  <Name xml:lang="no">Utdypende</Name>
  <Name xml:lang="pa">ਸ਼ਬਦ-ਆਡੰਬਰਪੂਰਣ</Name>
  <Name xml:lang="pl">Rozwlekły</Name>
  <Name xml:lang="pt">Descritivo</Name>
  <Name xml:lang="pt_BR">Prolixo</Name>
  <Name xml:lang="sq">Verbose</Name>
  <Name xml:lang="sr">Опширни</Name>
  <Name xml:lang="sr@Latn">Opširni</Name>
  <Name xml:lang="sv">Utförligt</Name>
  <Name xml:lang="ta">வர்போஸ்</Name>
  <Name xml:lang="tr">Ayırma</Name>
  <Name xml:lang="uk">Багатослівний</Name>
  <Name xml:lang="zh_CN">详细</Name>
  <Name xml:lang="zh_TW">詳細</Name>
  <Description>Give maximum speech and braille output.</Description>
  <Description xml:lang="ar">تلقّي أقصى مايمكن من إخراج الكلام و براي.</Description>
  <Description xml:lang="az">Maksimal danışıq və braille çıxışı ver.</Description>
  <Description xml:lang="bg">Максимален изход чрез реч и брайл</Description>
  <Description xml:lang="bn">সর্বোচ্চ ধ্বনি এবং ব্রেইল আউটপুট উপলব্ধ করো।</Description>
  <Description xml:lang="ca">Dóna la màxima sortida de la pronunciació i de braille.</Description>
  <Description xml:lang="cs">Určení maximálního výstupu řeči a braille.</Description>
  <Description xml:lang="cy">Rhoi allbwn llawn i&apos;r llais a braille</Description>
  <Description xml:lang="da">Giv maksimal uddata for tale og blindskrift.</Description>
  <Description xml:lang="de">Größtmögliche Sprach- und Braille-Ausgabe erzeugen.</Description>
  <Description xml:lang="el">Μέγιστο αποτέλεσμα λόγου και μπράΙγ.</Description>
  <Description xml:lang="en_CA">Give maximum speech and braille output.</Description>
  <Description xml:lang="en_GB">Give maximum speech and braille output.</Description>
  <Description xml:lang="es">Dar la máxima salida por voz y braille.</Description>
  <Description xml:lang="eu">Eman gehiengo irteera ahotsari eta braille-ari</Description>
  <Description xml:lang="fi">Käytä mahdollisimman paljon puhetta ja braillea.</Description>
  <Description xml:lang="gu">મહત્તમ બોલી અને બ્રેઈલ આઉટપુટ આપો.</Description>
  <Description xml:lang="hi">अधिकतम वाणी तथा ब्रेल आउटपुट दें</Description>
  <Description xml:lang="hr">Daje najviše govornog ili brialleovog izlaza.</Description>
  <Description xml:lang="it">Imposta al massino l&apos;output del sintetizzatore vocale e del braille</Description>
  <Description xml:lang="ja">最大音声出力と点字出力を指定して下さい。</Description>
  <Description xml:lang="ko">최대한 많은 음성 및 점자 출력을 내보냅니다.</Description>
  <Description xml:lang="lt">Duoti maksimalią kalbos ir brailio išvestį.</Description>
  <Description xml:lang="mn">Хамгийн и хэллэг ба braille гаралтыг өг.</Description>
  <Description xml:lang="nb">Gi maksimal tale- og blindeskriftinformasjon.</Description>
  <Description xml:lang="nl">Maximaal spraak en braille uitvoer geven.</Description>
  <Description xml:lang="no">Gi maksimal tale- og blindeskriftinformasjon.</Description>
  <Description xml:lang="pa">ਵੱਧ-ਤੋਂ-ਵੱਧ ਬੋਲੀ ਅਤੇ ਬ੍ਰੇਲ ਨਤੀਜਾ ਦਿਓ|</Description>
  <Description xml:lang="pl">Maksymalne wyjście mowy i braille&apos;a.</Description>
  <Description xml:lang="pt">Devolver resultado máximo de locução e braille.</Description>
  <Description xml:lang="pt_BR">Dar o máximo de saída por voz e em braile.</Description>
  <Description xml:lang="sq">Jep rezultatin maksimum të shqiptimit dhe braille.</Description>
  <Description xml:lang="sr">Користи највише могуће говорног и брајовог излаза.</Description>
  <Description xml:lang="sr@Latn">Koristi najviše moguće govornog i brajovog izlaza.</Description>
  <Description xml:lang="sv">Ge maximal utdata för tal och braille.</Description>
  <Description xml:lang="ta">அதிகபட்ச பேச்சு மற்றும் ப்ரெயில் வெளியீட்டை தரவும்</Description>
  <Description xml:lang="tr">Azami konuşma ve braille çıktısı ver.</Description>
  <Description xml:lang="uk">Озвучення з максимальними подробицями та вивід брайля.</Description>
  <Description xml:lang="zh_CN">给出最大语速和盲文输出。</Description>
  <Description xml:lang="zh_TW">給予最大的語音和點字輸出。</Description>
  <device name="braille">
    <presentation>
      <separator>
        <brdots dots="1278" />
      </separator>
      <role name="check-box">
        <event name="generic">
          <attribute type="string">role</attribute>
          <attribute type="string">name</attribute>
          <attribute type="string">(shortcut)</attribute>
          <conditional condition="state:checked" type="boolean">
            <true>

              <literal>(C)</literal>
              <literal xml:lang="ar">(C)</literal>
              <literal xml:lang="az">(C)</literal>
              <literal xml:lang="bg">(C)</literal>
              <literal xml:lang="bn">(C)</literal>
              <literal xml:lang="ca">(C)</literal>
              <literal xml:lang="cs">(Z)</literal>
              <literal xml:lang="cy">(C)</literal>
              <literal xml:lang="da">(A)</literal>
              <literal xml:lang="de">(C)</literal>
              <literal xml:lang="el">(C)</literal>
              <literal xml:lang="en_CA">(C)</literal>
              <literal xml:lang="en_GB">(C)</literal>
              <literal xml:lang="es">(C)</literal>
              <literal xml:lang="eu">(C)</literal>
              <literal xml:lang="fi">(V)</literal>
              <literal xml:lang="gu">(C)</literal>
              <literal xml:lang="hi">(C)</literal>
              <literal xml:lang="hr">(C)</literal>
              <literal xml:lang="it">(C)</literal>
              <literal xml:lang="ja">(C)</literal>
              <literal xml:lang="ko">(C)</literal>
              <literal xml:lang="lt">(C)</literal>
              <literal xml:lang="mn">(C)</literal>
              <literal xml:lang="nb">©</literal>
              <literal xml:lang="nl">(C)</literal>
              <literal xml:lang="no">©</literal>
              <literal xml:lang="pa">(C)</literal>
              <literal xml:lang="pl">(C)</literal>
              <literal xml:lang="pt">(C)</literal>
              <literal xml:lang="pt_BR">(C)</literal>
              <literal xml:lang="ru">(C)</literal>
              <literal xml:lang="sq">(C)</literal>
              <literal xml:lang="sr">(И)</literal>
              <literal xml:lang="sr@Latn">(I)</literal>
              <literal xml:lang="sv">(C)</literal>
              <literal xml:lang="ta">(C)</literal>
              <literal xml:lang="tr">(C)</literal>
              <literal xml:lang="uk">(C)</literal>
              <literal xml:lang="zh_CN">(C)</literal>
              <literal xml:lang="zh_TW">(C)</literal>
            </true>
          </conditional>
          <conditional condition="state:unchecked" type="boolean">
            <true>

              <literal>( )</literal>
              <literal xml:lang="ar">( )</literal>
              <literal xml:lang="az">( )</literal>
              <literal xml:lang="bg">( )</literal>
              <literal xml:lang="bn">( )</literal>
              <literal xml:lang="ca">( )</literal>
              <literal xml:lang="cs">( )</literal>
              <literal xml:lang="cy">( )</literal>
              <literal xml:lang="da">( )</literal>
              <literal xml:lang="de">( )</literal>
              <literal xml:lang="el">( )</literal>
              <literal xml:lang="en_CA">( )</literal>
              <literal xml:lang="en_GB">( )</literal>
              <literal xml:lang="es">( )</literal>
              <literal xml:lang="eu">( )</literal>
              <literal xml:lang="fi">( )</literal>
              <literal xml:lang="gu">( )</literal>
              <literal xml:lang="hi">( )</literal>
              <literal xml:lang="hr">( )</literal>
              <literal xml:lang="it">( )</literal>
              <literal xml:lang="ja">( )</literal>
              <literal xml:lang="ko">( )</literal>
              <literal xml:lang="lt">( )</literal>
              <literal xml:lang="mn">( )</literal>
              <literal xml:lang="ms"> </literal>
              <literal xml:lang="nb">()</literal>
              <literal xml:lang="nl">( )</literal>
              <literal xml:lang="no">()</literal>
              <literal xml:lang="pa">( )</literal>
              <literal xml:lang="pl">( )</literal>
              <literal xml:lang="pt">( )</literal>
              <literal xml:lang="pt_BR">( )</literal>
              <literal xml:lang="ru">( )</literal>
              <literal xml:lang="sq">( )</literal>
              <literal xml:lang="sr">( )</literal>
              <literal xml:lang="sr@Latn">( )</literal>
              <literal xml:lang="sv">( )</literal>
              <literal xml:lang="ta">( )</literal>
              <literal xml:lang="tr">( )</literal>
              <literal xml:lang="uk">( )</literal>
              <literal xml:lang="zh_CN">( )</literal>
              <literal xml:lang="zh_TW">( )</literal>
            </true>
          </conditional>
        </event>
        <event name="present">
          <attribute type="string">role</attribute>
          <attribute type="string">name</attribute>
          <attribute type="string">(shortcut)</attribute>
          <conditional condition="state:checked" type="boolean">
            <true>

              <literal>(C)</literal>
              <literal xml:lang="ar">(C)</literal>
              <literal xml:lang="az">(C)</literal>
              <literal xml:lang="bg">(C)</literal>
              <literal xml:lang="bn">(C)</literal>
              <literal xml:lang="ca">(C)</literal>
              <literal xml:lang="cs">(Z)</literal>
              <literal xml:lang="cy">(C)</literal>
              <literal xml:lang="da">(A)</literal>
              <literal xml:lang="de">(C)</literal>
              <literal xml:lang="el">(C)</literal>
              <literal xml:lang="en_CA">(C)</literal>
              <literal xml:lang="en_GB">(C)</literal>
              <literal xml:lang="es">(C)</literal>
              <literal xml:lang="eu">(C)</literal>
              <literal xml:lang="fi">(V)</literal>
              <literal xml:lang="gu">(C)</literal>
              <literal xml:lang="hi">(C)</literal>
              <literal xml:lang="hr">(C)</literal>
              <literal xml:lang="it">(C)</literal>
              <literal xml:lang="ja">(C)</literal>
              <literal xml:lang="ko">(C)</literal>
              <literal xml:lang="lt">(C)</literal>
              <literal xml:lang="mn">(C)</literal>
              <literal xml:lang="nb">©</literal>
              <literal xml:lang="nl">(C)</literal>
              <literal xml:lang="no">©</literal>
              <literal xml:lang="pa">(C)</literal>
              <literal xml:lang="pl">(C)</literal>
              <literal xml:lang="pt">(C)</literal>
              <literal xml:lang="pt_BR">(C)</literal>
              <literal xml:lang="ru">(C)</literal>
              <literal xml:lang="sq">(C)</literal>
              <literal xml:lang="sr">(И)</literal>
              <literal xml:lang="sr@Latn">(I)</literal>
              <literal xml:lang="sv">(C)</literal>
              <literal xml:lang="ta">(C)</literal>
              <literal xml:lang="tr">(C)</literal>
              <literal xml:lang="uk">(C)</literal>
              <literal xml:lang="zh_CN">(C)</literal>
              <literal xml:lang="zh_TW">(C)</literal>
            </true>
	  </conditional>
          <conditional condition="state:unchecked" type="boolean">
            <true>

              <literal>( )</literal>
              <literal xml:lang="ar">( )</literal>
              <literal xml:lang="az">( )</literal>
              <literal xml:lang="bg">( )</literal>
              <literal xml:lang="bn">( )</literal>
              <literal xml:lang="ca">( )</literal>
              <literal xml:lang="cs">( )</literal>
              <literal xml:lang="cy">( )</literal>
              <literal xml:lang="da">( )</literal>
              <literal xml:lang="de">( )</literal>
              <literal xml:lang="el">( )</literal>
              <literal xml:lang="en_CA">( )</literal>
              <literal xml:lang="en_GB">( )</literal>
              <literal xml:lang="es">( )</literal>
              <literal xml:lang="eu">( )</literal>
              <literal xml:lang="fi">( )</literal>
              <literal xml:lang="gu">( )</literal>
              <literal xml:lang="hi">( )</literal>
              <literal xml:lang="hr">( )</literal>
              <literal xml:lang="it">( )</literal>
              <literal xml:lang="ja">( )</literal>
              <literal xml:lang="ko">( )</literal>
              <literal xml:lang="lt">( )</literal>
              <literal xml:lang="mn">( )</literal>
              <literal xml:lang="ms"> </literal>
              <literal xml:lang="nb">()</literal>
              <literal xml:lang="nl">( )</literal>
              <literal xml:lang="no">()</literal>
              <literal xml:lang="pa">( )</literal>
              <literal xml:lang="pl">( )</literal>
              <literal xml:lang="pt">( )</literal>
              <literal xml:lang="pt_BR">( )</literal>
              <literal xml:lang="ru">( )</literal>
              <literal xml:lang="sq">( )</literal>
              <literal xml:lang="sr">( )</literal>
              <literal xml:lang="sr@Latn">( )</literal>
              <literal xml:lang="sv">( )</literal>
              <literal xml:lang="ta">( )</literal>
              <literal xml:lang="tr">( )</literal>
              <literal xml:lang="uk">( )</literal>
              <literal xml:lang="zh_CN">( )</literal>
              <literal xml:lang="zh_TW">( )</literal>
            </true>
          </conditional>
          <conditional condition="state:enabled" type="boolean">
            <false>

              <literal>(U)</literal>
              <literal xml:lang="ar">(U)</literal>
              <literal xml:lang="az">(U)</literal>
              <literal xml:lang="bg">(U)</literal>
              <literal xml:lang="bn">(U)</literal>
              <literal xml:lang="ca">(U)</literal>
              <literal xml:lang="cs">(N)</literal>
              <literal xml:lang="cy">(U)</literal>
              <literal xml:lang="da">(I)</literal>
              <literal xml:lang="de">(U)</literal>
              <literal xml:lang="el">(U)</literal>
              <literal xml:lang="en_CA">(U)</literal>
              <literal xml:lang="en_GB">(U)</literal>
              <literal xml:lang="es">(U)</literal>
              <literal xml:lang="eu">(U)</literal>
              <literal xml:lang="fi">(U)</literal>
              <literal xml:lang="gu">(U)</literal>
              <literal xml:lang="hi">(यू)</literal>
              <literal xml:lang="hr">(U)</literal>
              <literal xml:lang="it">(U)</literal>
              <literal xml:lang="ja">(U)</literal>
              <literal xml:lang="ko">(U)</literal>
              <literal xml:lang="lt">(U)</literal>
              <literal xml:lang="mn">(U)</literal>
              <literal xml:lang="nb">(U)</literal>
              <literal xml:lang="nl">(U)</literal>
              <literal xml:lang="no">(U)</literal>
              <literal xml:lang="pa">(U)</literal>
              <literal xml:lang="pl">(U)</literal>
              <literal xml:lang="pt">(U)</literal>
              <literal xml:lang="pt_BR">(U)</literal>
              <literal xml:lang="ru">(U)</literal>
              <literal xml:lang="sq">(U)</literal>
              <literal xml:lang="sr">(Н)</literal>
              <literal xml:lang="sr@Latn">(N)</literal>
              <literal xml:lang="sv">(U)</literal>
              <literal xml:lang="ta">(U)</literal>
              <literal xml:lang="tr">(U)</literal>
              <literal xml:lang="uk">(U)</literal>
              <literal xml:lang="zh_CN">(U)</literal>
              <literal xml:lang="zh_TW">(U)</literal>
            </false>
          </conditional>
        </event>
      </role>
      <role name="check-menu-item">
        <event name="generic">
          <attribute type="string">role</attribute>
          <attribute type="string">name</attribute>
          <attribute type="string">(accelerator)</attribute>
          <attribute type="string">(shortcut)</attribute>
          <conditional condition="state:checked" type="boolean">
            <true>

              <literal>(C)</literal>
              <literal xml:lang="ar">(C)</literal>
              <literal xml:lang="az">(C)</literal>
              <literal xml:lang="bg">(C)</literal>
              <literal xml:lang="bn">(C)</literal>
              <literal xml:lang="ca">(C)</literal>
              <literal xml:lang="cs">(Z)</literal>
              <literal xml:lang="cy">(C)</literal>
              <literal xml:lang="da">(A)</literal>
              <literal xml:lang="de">(C)</literal>
              <literal xml:lang="el">(C)</literal>
              <literal xml:lang="en_CA">(C)</literal>
              <literal xml:lang="en_GB">(C)</literal>
              <literal xml:lang="es">(C)</literal>
              <literal xml:lang="eu">(C)</literal>
              <literal xml:lang="fi">(V)</literal>
              <literal xml:lang="gu">(C)</literal>
              <literal xml:lang="hi">(C)</literal>
              <literal xml:lang="hr">(C)</literal>
              <literal xml:lang="it">(C)</literal>
              <literal xml:lang="ja">(C)</literal>
              <literal xml:lang="ko">(C)</literal>
              <literal xml:lang="lt">(C)</literal>
              <literal xml:lang="mn">(C)</literal>
              <literal xml:lang="nb">©</literal>
              <literal xml:lang="nl">(C)</literal>
              <literal xml:lang="no">©</literal>
              <literal xml:lang="pa">(C)</literal>
              <literal xml:lang="pl">(C)</literal>
              <literal xml:lang="pt">(C)</literal>
              <literal xml:lang="pt_BR">(C)</literal>
              <literal xml:lang="ru">(C)</literal>
              <literal xml:lang="sq">(C)</literal>
              <literal xml:lang="sr">(И)</literal>
              <literal xml:lang="sr@Latn">(I)</literal>
              <literal xml:lang="sv">(C)</literal>
              <literal xml:lang="ta">(C)</literal>
              <literal xml:lang="tr">(C)</literal>
              <literal xml:lang="uk">(C)</literal>
              <literal xml:lang="zh_CN">(C)</literal>
              <literal xml:lang="zh_TW">(C)</literal>
            </true>
	  </conditional>
	  <conditional condition="state:unchecked" type="boolean">
            <true>

              <literal>( )</literal>
              <literal xml:lang="ar">( )</literal>
              <literal xml:lang="az">( )</literal>
              <literal xml:lang="bg">( )</literal>
              <literal xml:lang="bn">( )</literal>
              <literal xml:lang="ca">( )</literal>
              <literal xml:lang="cs">( )</literal>
              <literal xml:lang="cy">( )</literal>
              <literal xml:lang="da">( )</literal>
              <literal xml:lang="de">( )</literal>
              <literal xml:lang="el">( )</literal>
              <literal xml:lang="en_CA">( )</literal>
              <literal xml:lang="en_GB">( )</literal>
              <literal xml:lang="es">( )</literal>
              <literal xml:lang="eu">( )</literal>
              <literal xml:lang="fi">( )</literal>
              <literal xml:lang="gu">( )</literal>
              <literal xml:lang="hi">( )</literal>
              <literal xml:lang="hr">( )</literal>
              <literal xml:lang="it">( )</literal>
              <literal xml:lang="ja">( )</literal>
              <literal xml:lang="ko">( )</literal>
              <literal xml:lang="lt">( )</literal>
              <literal xml:lang="mn">( )</literal>
              <literal xml:lang="ms"> </literal>
              <literal xml:lang="nb">()</literal>
              <literal xml:lang="nl">( )</literal>
              <literal xml:lang="no">()</literal>
              <literal xml:lang="pa">( )</literal>
              <literal xml:lang="pl">( )</literal>
              <literal xml:lang="pt">( )</literal>
              <literal xml:lang="pt_BR">( )</literal>
              <literal xml:lang="ru">( )</literal>
              <literal xml:lang="sq">( )</literal>
              <literal xml:lang="sr">( )</literal>
              <literal xml:lang="sr@Latn">( )</literal>
              <literal xml:lang="sv">( )</literal>
              <literal xml:lang="ta">( )</literal>
              <literal xml:lang="tr">( )</literal>
              <literal xml:lang="uk">( )</literal>
              <literal xml:lang="zh_CN">( )</literal>
              <literal xml:lang="zh_TW">( )</literal>
            </true>
          </conditional>
          <conditional condition="state:enabled" type="boolean">
            <false>

              <literal>(U)</literal>
              <literal xml:lang="ar">(U)</literal>
              <literal xml:lang="az">(U)</literal>
              <literal xml:lang="bg">(U)</literal>
              <literal xml:lang="bn">(U)</literal>
              <literal xml:lang="ca">(U)</literal>
              <literal xml:lang="cs">(N)</literal>
              <literal xml:lang="cy">(U)</literal>
              <literal xml:lang="da">(I)</literal>
              <literal xml:lang="de">(U)</literal>
              <literal xml:lang="el">(U)</literal>
              <literal xml:lang="en_CA">(U)</literal>
              <literal xml:lang="en_GB">(U)</literal>
              <literal xml:lang="es">(U)</literal>
              <literal xml:lang="eu">(U)</literal>
              <literal xml:lang="fi">(U)</literal>
              <literal xml:lang="gu">(U)</literal>
              <literal xml:lang="hi">(यू)</literal>
              <literal xml:lang="hr">(U)</literal>
              <literal xml:lang="it">(U)</literal>
              <literal xml:lang="ja">(U)</literal>
              <literal xml:lang="ko">(U)</literal>
              <literal xml:lang="lt">(U)</literal>
              <literal xml:lang="mn">(U)</literal>
              <literal xml:lang="nb">(U)</literal>
              <literal xml:lang="nl">(U)</literal>
              <literal xml:lang="no">(U)</literal>
              <literal xml:lang="pa">(U)</literal>
              <literal xml:lang="pl">(U)</literal>
              <literal xml:lang="pt">(U)</literal>
              <literal xml:lang="pt_BR">(U)</literal>
              <literal xml:lang="ru">(U)</literal>
              <literal xml:lang="sq">(U)</literal>
              <literal xml:lang="sr">(Н)</literal>
              <literal xml:lang="sr@Latn">(N)</literal>
              <literal xml:lang="sv">(U)</literal>
              <literal xml:lang="ta">(U)</literal>
              <literal xml:lang="tr">(U)</literal>
              <literal xml:lang="uk">(U)</literal>
              <literal xml:lang="zh_CN">(U)</literal>
              <literal xml:lang="zh_TW">(U)</literal>
            </false>
          </conditional>
        </event>
      </role>
      <role name="combo-box">
        <event name="generic">
          <attribute type="string">role</attribute>
          <attribute type="string">name</attribute>
          <attribute type="string">text:line</attribute>
        </event>
      </role>
      <role name="edit-bar">
        <event name="generic">
          <attribute type="string">role</attribute>
          <attribute type="string">name</attribute>
          <attribute type="string">text:line</attribute>
        </event>
      </role>
      <role name="generic">
        <event name="generic">
          <attribute type="string">role</attribute>
          <attribute type="string">name</attribute>
        </event>
      </role>
      <role name="link">
        <event name="generic">
          <attribute type="string">role</attribute>
          <attribute type="string">text:line</attribute>
        </event>
      </role>
      <role name="list">
        <event name="generic">
          <attribute type="string">role</attribute>
          <attribute type="string">name</attribute>
          <attribute type="int">childcount</attribute>
          <conditional condition="childcount=1" type="gboolean">
            <true>
              <literal>item</literal>
            </true>
            <false>
              <literal>items</literal>
              <literal xml:lang="ar">عناصر</literal>
              <literal xml:lang="az">üzvlər</literal>
              <literal xml:lang="bg">елементи</literal>
              <literal xml:lang="bn">বস্তু</literal>
              <literal xml:lang="ca">elements</literal>
              <literal xml:lang="cs">položek</literal>
              <literal xml:lang="cy">eitemau</literal>
              <literal xml:lang="da">elementer</literal>
              <literal xml:lang="de">Objekt</literal>
              <literal xml:lang="el">αντικείμενα</literal>
              <literal xml:lang="en_CA">items</literal>
              <literal xml:lang="en_GB">items</literal>
              <literal xml:lang="es">elementos</literal>
              <literal xml:lang="eu">elementuak</literal>
              <literal xml:lang="fi">kohteet</literal>
              <literal xml:lang="gu">વસ્તુઓ</literal>
              <literal xml:lang="hi">वस्तुएँ</literal>
              <literal xml:lang="hr">stavaka</literal>
              <literal xml:lang="it">elementi</literal>
              <literal xml:lang="ja">項目</literal>
              <literal xml:lang="ko">항목</literal>
              <literal xml:lang="lt">elementai</literal>
              <literal xml:lang="mn">Элемэнтүүд</literal>
              <literal xml:lang="ms">item</literal>
              <literal xml:lang="nb">oppføringer</literal>
              <literal xml:lang="nl">items</literal>
              <literal xml:lang="no">oppføringer</literal>
              <literal xml:lang="pa">ਇਕਾਈਆਂ</literal>
              <literal xml:lang="pl">elementy</literal>
              <literal xml:lang="pt">itens</literal>
              <literal xml:lang="pt_BR">itens</literal>
              <literal xml:lang="ru">элементы</literal>
              <literal xml:lang="sq">elementët</literal>
              <literal xml:lang="sr">ставки</literal>
              <literal xml:lang="sr@Latn">stavki</literal>
              <literal xml:lang="sv">objekt</literal>
              <literal xml:lang="ta">உருப்படிகள்</literal>
              <literal xml:lang="tr">öğeler</literal>
              <literal xml:lang="uk">елементів</literal>
              <literal xml:lang="zh_CN">项</literal>
              <literal xml:lang="zh_TW">項目</literal>
            </false>
          </conditional>
        </event>
      </role>
      <role name="list-item">
        <event name="generic">
          <attribute type="string">role</attribute>
          <attribute type="string">name</attribute>
          <attribute type="string">(shortcut)</attribute>
        </event>
      </role>
      <role name="menu-bar">
        <event name="generic">
          <attribute type="string">role</attribute>
          <attribute type="string">name</attribute>
          <children sep="1237">
            <attribute type="string">name</attribute>
          </children>
        </event>
      </role>
      <role name="menu">
        <event name="generic">
          <attribute type="string">role</attribute>
          <attribute type="string">name</attribute>